# Generated by Django 3.0.3 on 2020-05-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category/'),
        ),
    ]
