# Generated by Django 3.0.3 on 2020-05-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20200515_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='timestamp',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
