# Generated by Django 3.0.3 on 2020-05-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_reserve_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
