# Generated by Django 3.0.3 on 2020-05-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20200516_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
