# Generated by Django 3.0.3 on 2020-05-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20200516_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='reserve',
            name='shirt_size',
            field=models.CharField(choices=[('3 Bedroom Apartment', '3 Bedroom Apartment'), ('M', 'Medium')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
