# Generated by Django 3.0.3 on 2020-05-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_remove_reserve_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='shirt_size',
        ),
        migrations.AddField(
            model_name='reserve',
            name='notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
